In [2]:
import numpy as np
a = np.array([[4/15, 5/15, 6/15],
             [1/15,13/15,1/15],
             [13/15,1/15,1/15]])

In [3]:
a = np.matrix(a)
x0 = np.matrix([1/3,1/3,1/3])
x0,a

(matrix([[0.33333333, 0.33333333, 0.33333333]]),
 matrix([[0.26666667, 0.33333333, 0.4       ],
         [0.06666667, 0.86666667, 0.06666667],
         [0.86666667, 0.06666667, 0.06666667]]))

In [4]:
#for i in range(0,6):
 #   x0 = x0*a**i
 #   print(" Iteration " + str(i) + " : " + str(x0))

#5th iteration
x0*a**5

matrix([[0.24663704, 0.60205432, 0.15130864]])

In [5]:
a0 = x0*a**0
a1 = x0*a**1
a2 = x0*a**2
a3 = x0*a**3
a4 = x0*a**4
a5 = x0*a**5
a6 = x0*a**6
a7 = x0*a**7
a8 = x0*a**8
a9 = x0*a**9
a10 = x0*a**10
a11 = x0*a**11
a12 = x0*a**12

In [8]:
print("2",a2-a1,a2-a1 <= [0.001,0.001,0.001])
print("3",a3-a2,a3-a2 <= [0.001,0.001,0.001])
print("2",a4-a3,a4-a3 <= [0.001,0.001,0.001])
print("2",a5-a4,a5-a4 <= [0.001,0.001,0.001])
print("2",a6-a5,a6-a5 <= [0.001,0.001,0.001])
print("2",a7-a6,a7-a6 <= [0.001,0.001,0.001])
print("2",a8-a7,a8-a7 <= [0.001,0.001,0.001])
print("2",a9-a8,a9-a8 <= [0.001,0.001,0.001])
print("2",a10-a9,a10-a9 <= [0.001,0.001,0.001])
print("2",a11-a10,a11-a10 <= [0.001,0.001,0.001])
print("2",a12-a11,a12-a11 <= [0.001,0.001,0.001])

2 [[-0.11111111  0.08888889  0.02222222]] [[ True False False]]
3 [[-0.00444444  0.04148148 -0.03703704]] [[ True False  True]]
2 [[-0.03051852  0.032      -0.00148148]] [[ True False  True]]
2 [[-0.00728889  0.01746173 -0.01017284]] [[ True False  True]]
2 [[-0.00959605  0.01202568 -0.00242963]] [[ True False  True]]
2 [[-0.00386291  0.0070616  -0.00319868]] [[ True False  True]]
2 [[-0.00333153  0.00461917 -0.00128764]] [[ True False  True]]
2 [[-0.00169642  0.00280693 -0.00111051]] [[ True False  True]]
2 [[-0.00122769  0.00179316 -0.00056547]] [[ True False  True]]
2 [[-0.00069792  0.00110715 -0.00040923]] [[ True False  True]]
2 [[-0.00046697  0.00069961 -0.00023264]] [[ True  True  True]]


matrix([[-0.11111111,  0.08888889,  0.02222222]])