In [1]:
import numpy as np
matrix = [[0,1,1,0,0,1],
         [0,0,0,0,0,1],
         [1,0,0,1,1,0],
         [1,0,0,0,0,1],
         [0,1,0,0,0,0],
         [0,0,0,0,0,0]]

In [2]:
def stochastic(matrix,alpha):
    new_m = np.zeros((len(matrix[0]),len(matrix[0])))
    for i in range(0,len(matrix[0])):
        for j in range(0,len(matrix[0])):
            if(sum(matrix[i])==0):
                new_m[i][j] = 1/len(matrix[0])
            else:
                if(matrix[i][j] == 0):
                    new_m[i][j] = alpha/len(matrix[0])
                else:
                    new_m[i][j] = (alpha/len(matrix[0])) + ((1-alpha) * (1/sum(matrix[i])))
    return new_m

In [3]:
m = stochastic(matrix,0.2)
m

array([[0.03333333, 0.3       , 0.3       , 0.03333333, 0.03333333,
        0.3       ],
       [0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333,
        0.83333333],
       [0.3       , 0.03333333, 0.03333333, 0.3       , 0.3       ,
        0.03333333],
       [0.43333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333,
        0.43333333],
       [0.03333333, 0.83333333, 0.03333333, 0.03333333, 0.03333333,
        0.03333333],
       [0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
        0.16666667]])

In [4]:
def rank_calc(stm,X):
    c = len(stm.sum(axis=1))
    prob = 1/c
    vec_x0 = np.full((1,c),prob)
    print("intial vetor",vec_x0)
    while(X!=0):
        vec_x0 = np.dot(vec_x0,stm)
        X = X-1
        print(vec_x0)

In [8]:
rank_calc(m,5)

intial vetor [[0.2 0.2 0.2 0.2 0.2]]
[[0.232      0.20533333 0.12533333 0.20533333 0.232     ]]
[[0.26272    0.21400889 0.13187556 0.21400889 0.17738667]]
[[0.27855787 0.21105446 0.1254509  0.21105446 0.17388231]]
[[0.29066746 0.20852414 0.12410236 0.20852414 0.16818189]]
[[0.29944307 0.2059252  0.12251554 0.2059252  0.16619099]]
