In [1]:
import numpy as np

arr = np.array([1, 29, 34, 432, 133, 76, 97, 8, 9])

print(arr)

[  1  29  34 432 133  76  97   8   9]


In [8]:
new_arr = arr[1:5]
new_arr

array([ 29,  34, 432, 133])

In [9]:
new_arr2 = arr[:4]
new_arr2

array([  1,  29,  34, 432])

In [10]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr3 = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [12]:
new_arr = np.hstack((arr2, arr3))
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [13]:
new_arr = np.vstack((arr2, arr3))
new_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [14]:
new_arr = np.stack((arr2, arr3))
new_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [16]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])